[package]
name = "first_project"
version = "0.1.0"
authors = ["paladinbaby <308257336@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
